### ISSUE TITLE
Erro ao resolver dependência da Senior

### ISSUE THREAD

**Issue by gfmedeiros** [brenonaraujo/dev-na-pratica-basico#4]
Prezados,

Ao executar meu projeto fora da FURB, não consigo resolver as dependências da Sênior. Por exemplo:

```bash
cd java/impl
mvn package
```
Mensagem de erro:

> [INFO] Scanning for projects...
> [INFO]
> [INFO] ----------------< br.com.senior.furb:furb-basico-impl >-----------------
> [INFO] Building furb-basico-impl develop-SNAPSHOT
> [INFO] --------------------------------[ jar ]---------------------------------
> Downloading from snapshots: http://maven.senior.com.br:8081/artifactory/libs-snapshot/br/com/senior/furb/furb-basico-server/develop-SNAPSHOT/maven-metadata.xml
> [WARNING] Could not transfer metadata br.com.senior.furb:furb-basico-server:develop-SNAPSHOT/maven-metadata.xml from/to snapshots
> (http://maven.senior.com.br:8081/artifactory/libs-snapshot): Este host não é conhecido (maven.senior.com.br)
> [WARNING] Failure to transfer br.com.senior.furb:furb-basico-server:develop-SNAPSHOT/maven-metadata.xml from http://maven.senior.com.br:8081/artifactory/libs-snapshot was cached in the local repository, resolution will not be reattempted until the update interval of snapshots has elapsed or updates are forced. Original error: Could not transfer metadata br.com.senior.furb:furb-basico-server:develop-SNAPSHOT/maven-metadata.xml from/to snapshots (http://maven.senior.com.br:8081/artifactory/libs-snapshot): Este host não é conhecido (maven.senior.com.br)
> Downloading from snapshots: http://maven.senior.com.br:8081/artifactory/libs-snapshot/br/com/senior/furb/furb-basico-server/develop-SNAPSHOT/furb-basico-server-develop-SNAPSHOT.pom
> Downloading from central: http://maven.senior.com.br:8081/artifactory/libs-release/org/postgresql/postgresql/42.1.1/postgresql-42.1.1.pom
> Downloading from snapshots: http://maven.senior.com.br:8081/artifactory/libs-snapshot/org/postgresql/postgresql/42.1.1/postgresql-42.1.1.pom
> Downloading from central: http://maven.senior.com.br:8081/artifactory/libs-release/oracle/ojdbc6/11.2.0.1.0/ojdbc6-11.2.0.1.0.pom
> Downloading from snapshots: http://maven.senior.com.br:8081/artifactory/libs-snapshot/oracle/ojdbc6/11.2.0.1.0/ojdbc6-11.2.0.1.0.pom
> Downloading from central: http://maven.senior.com.br:8081/artifactory/libs-release/net/sourceforge/jtds/jtds/1.3.1/jtds-1.3.1.pom
> Downloading from snapshots: http://maven.senior.com.br:8081/artifactory/libs-snapshot/net/sourceforge/jtds/jtds/1.3.1/jtds-1.3.1.pom
> Downloading from central: http://maven.senior.com.br:8081/artifactory/libs-release/com/h2database/h2/1.4.197/h2-1.4.197.pom
> Downloading from snapshots: http://maven.senior.com.br:8081/artifactory/libs-snapshot/com/h2database/h2/1.4.197/h2-1.4.197.pom
> Downloading from central: http://maven.senior.com.br:8081/artifactory/libs-release/br/com/senior/translation-hub-api-test/2.3.1/translation-hub-api-test-2.3.1.pom
> Downloading from snapshots: http://maven.senior.com.br:8081/artifactory/libs-snapshot/br/com/senior/translation-hub-api-test/2.3.1/translation-hub-api-test-2.3.1.pom
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  0.784 s
> [INFO] Finished at: 2019-06-20T15:49:15-03:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project furb-basico-impl: Could not resolve dependencies for project br.com.senior.furb:furb-basico-impl:jar:develop-SNAPSHOT: Failed to collect dependencies at br.com.senior.furb:furb-basico-server:jar:develop-SNAPSHOT: Failed to read artifact descriptor for br.com.senior.furb:furb-basico-server:jar:develop-SNAPSHOT: Could not transfer artifact br.com.senior.furb:furb-basico-server:pom:develop-SNAPSHOT from/to snapshots (http://maven.senior.com.br:8081/artifactory/libs-snapshot):
> maven.senior.com.br: Unknown host maven.senior.com.br -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Eu consigo fazer o ping do host senior.com.br sem problemas, mas maven.senior.com.br não. Podem averiguar?

Link do meu projeto: https://github.com/gfmedeiros/dev-na-pratica.git

**Comment by gpiske** [comment]
Estou com o mesmo problema.

Erro:
![erro](https://user-images.githubusercontent.com/21672714/59890827-2588f700-93a9-11e9-89e3-c1f832dbbb20.PNG)

**Comment by fredy-senior** [comment]
@gfmedeiros @gpiske no arquivo sdl.properties, altere a propriedade **generator.java.parent.pom.generate** para **false** (Atualmente ela está com o valor true). Quando esta propriedade está com o valor true, o arquivo java/pom.xml sempre é regerado e os repositórios maven.senior.com.br são referenciados novamente.

Após realizar a alteração no sdl.properties, altere o arquivo **java/pom.xml** removendo a tag **distributionManagement** e substituindo o conteúdo da tag **repositories** pelo conteúdo abaixo:
```
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>senior-libs-release</id>
            <url>http://maven.devnapratica.senior.com.br:8081/artifactory/libs-release</url>
        </repository>
        <repository>
            <snapshots/>
            <id>snapshots</id>
            <name>libs-snapshot</name>
            <url>http://maven.devnapratica.senior.com.br:8081/artifactory/libs-snapshot</url>
        </repository>
```

**Comment by gfmedeiros** [comment]
Consegui baixar as dependências. Ainda não consigo compilar usando somente o `mvn`, mas através do Eclipse funciona. 

Nota: vou precisar alterar o **.gitignore** do projeto, já que tivemos que alterar o arquivo **java/pom.xml**, que teoricamente é auto-gerado.

Por mim pode fechar o incidente. Deu certo, @gpiske?

**Comment by gpiske** [comment]
Deu certo também, muito obrigado.

Em seg, 24 de jun de 2019 às 10:25, Gabriel Felipe Medeiros <
notifications@github.com> escreveu:
