### ISSUE TITLE
Acesso à Queries e Actions

### ISSUE THREAD

**Issue by felaugmar** [brenonaraujo/dev-na-pratica-basico#7]
Posso acessar tanto uma _query_ como uma _action_ pela url `...rest/furb/basico/queries/...`
e o mesmo pela url `...rest/furb/basico/actions/...`.

Isso era para ser assim?

**Comment by fredy-senior** [comment]
@felaugmar sim, o que muda é apenas o termo queries e actions.
- Para chamar uma **query**, a URL fica: https://platform-homologx.senior.com.br/t/senior.com.br/bridge/1.0/rest/furb/basico/queries/NOMEQUERY
- Para chamar uma **action**, a URL fica: https://platform-homologx.senior.com.br/t/senior.com.br/bridge/1.0/rest/furb/basico/actions/NOMEQUERY

Ambos aceitam os verbos HTTP GET e POST.
